spring:
  datasource:
    url: jdbc:mysql://localhost:3306/im?useSSL=false&zeroDateTimeBehavior=convertToNull
    password: 896757055
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: dev
logging:
  config: classpath:logback-spring.xml
  path: E:/log